server:
  port: ${PORT:8080}

spring:
  application:
    name: LiveInterview

  datasource:
    url: jdbc:postgresql://localhost:5432/live_interview
    username: tanish
    password: 12345678
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    jwt:
      secret: mySuperSecretJwtKey_ChangeThisInProd_123456
      expiration: 86400000

  rabbitmq:
    host: localhost
    port: 5672
    username: live_interview
    password: secret123

  sql:
    init:
      platform: postgres

  debug: true

